import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/common/Footer';
import ToggleDarkMode from '@/components/common/ToggleDarkMode';
import { Analytics } from '@vercel/analytics/react';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

const DEFAULT_TITLE = '박정규의 블로그';

export const metadata: Metadata = {
  title: { default: DEFAULT_TITLE, template: `%s | ${DEFAULT_TITLE}` },
  description: 'Generated by create next app',
  verification: {
    google: 'QXCt1rHR8GlnfcaX2CeaMmTAyjZnHME4405PEA_aZHE',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-DLKNCH0H7D', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
      </head>
      <Script
        strategy="afterInteractive"
        src={'https://www.googletagmanager.com/gtag/js?id=G-DLKNCH0H7D'}
      />
      <body className={inter.className}>
        <ToggleDarkMode />
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
